### PR TITLE
Drop external tests

### PR DESCRIPTION
**Pull request by jdinan**
Please review carefully.  Our new testing strategy is to utilize the external test suites directly, rather than embedding and maintaining them in the Sandia SHMEM repository.

### CODE REVIEW

**Comment by jdinan** [comment]
PR #37 should be closed without merging, if we accept this PR.

**Comment by kseager** [comment]
This looks good to me; Ryan could you review and merge?

**Comment by kseager** [comment]
This would also close issue #43 #44 since we're moving to an external test suite model. Can you update your commit for this?

**Comment by jdinan** [comment]
Thanks -- you already did it.  :)  Github automatically added a cross-link to your comment.  Rather than updating the commit messages (which is a pain), whoever merges this PR can reference those issues in the merge message.

**Pull request merged**
